### ISSUE TITLE
How can i configuration setting?

### ISSUE THREAD

**Issue by kooku0** [juanallo/vscode-dependency-cruiser#10]
Hello, I use this extension.
Default of maxDepth is 0 level. I want see more depth. how can i do?

**Comment by kokofirstlove** [comment]
0

**Comment by fbruckhoff** [comment]
+1 for better documentation about where to configure the extension. I couldn't find it either.

**Comment by paulosborne** [comment]
I'm also looking for a configurable depth setting 👍🏻
