### ISSUE TITLE
How it is compared to depcheck?

### ISSUE THREAD

**Issue by zardoy** [juanallo/vscode-dependency-cruiser#12]
AFAIK depcheck by far is the most comprehensive tool for analyzing dependency tree, does this extension only detect js files? Would be great to describe it in readme. I have had the idea for depcheck extension some time ago…

**Comment by juanallo** [comment]
Hi, 
I need to check a little bit more depcheck but this plugin is based on this other tool: npmjs.com/package/dependency-cruiser which is mainly for js/TS ecosystem.

It's using that under the hood to do the analysis. My goal is to provide a UI on top of it that would let you filter and organize the automatic visualization to make more sense of it. The main goal was to give you a good way of visualizing dependencies. I find this sometimes hard on TS/JS.

What would be some use cases you had in mind?

**Comment by zardoy** [comment]
Sorry for the latency. I looked into dependency-cruiser and now I understand that there are different. dependency-cruiser builds TypeScript import graphs, while depcheck is focused on detecting which `package.json` dependencies are in usage, which are missing in package.json but used in the code and finally which are not used and can be removed. It mainly focused on "just find any usage", without even reporting location in files. It looked promising since it has [special detectors](https://github.com/depcheck/depcheck/tree/main/src/special), e.g. it can detect that dependency referened in package.json script.

I just wanted to try it on real projects, so built https://github.com/zardoy/vscode-depcheck and even UI is absolutely different
![image](https://user-images.githubusercontent.com/46503702/142995396-a4195c3d-3a2f-4385-ab06-848817adefe1.png)

I'll probably try to improve to location detections and finally make it possible to bundle..
